<a href="https://colab.research.google.com/github/JoseLibardo/Chapter4/blob/master/Numpy_Challenge_Resuelto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [3]:
import numpy as np

arreglo = np.array([7, 8, 4, 5, 1, 2])

Using slicing print the elements from index 3 to the end of the array.



In [4]:
print(arreglo[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [ ]:
print(arreglo[:5])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [ ]:
print(arreglo[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [5]:
newarr = arreglo.reshape(3, 2)
print(newarr)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [6]:
for x in arreglo:
  print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [7]:
arreglo2 = np.array([0, 6, 9])

Join the two arrays.



In [9]:
arreglototal = np.concatenate((arreglo, arreglo2))
print(arreglototal)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [11]:
x = [True, False, False, True, True, False, False, False, True]

newarr = arreglototal[x]

print(newarr)

[7 5 1 9]


Sort the joined array elements.



In [ ]:
print(np.sort(arreglototal))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [ ]:
arreglomeses = np.array(['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'], dtype='S') 

print(arreglomeses)

[b'enero' b'febrero' b'marzo' b'abril' b'mayo' b'junio' b'julio' b'agosto'
 b'septiembre' b'octubre' b'noviembre' b'diciembre']


Split the months array in 4 periods of 3 elements each one.



In [13]:
arreglomeses = np.array(['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'], dtype='S') 

newarreglo2 = np.array_split(arreglomeses, 4)
print(newarreglo2)

[array([b'enero', b'febrero', b'marzo'], dtype='|S10'), array([b'abril', b'mayo', b'junio'], dtype='|S10'), array([b'julio', b'agosto', b'septiembre'], dtype='|S10'), array([b'octubre', b'noviembre', b'diciembre'], dtype='|S10')]


Create an array with genre information ['F','M','F','F','M','F'].



In [14]:
arreglo = np.array(['F','M','F','F','M','F'], dtype='S')

Find the indexes where the value is F.



In [17]:
newarreglo = arreglo.astype(str)

x = np.where(newarreglo == 'F')
print(x)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [32]:
arregloa = np.array([18,20,19,23,19,20])

Create a filter array with values < 20.



In [37]:
filter_arregloa = arra < 20
newarraglo = arra[filter_arregloa]
print(newarraglo)


[18 19 19]


Change the 3 index element with a value of 22



In [38]:
print(arra[3]-1)

22


Print the 4 index element.

In [39]:
print(arra[4])

19
